# Generated by Django 3.2.4 on 2021-11-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='brief',
            field=models.TextField(default='', max_length=50),
        ),
    ]
